### ISSUE TITLE
謝謝您親切的回答

### ISSUE THREAD

**Issue by arguskao** [seriaati/591-notify#4]
我按照您的說明操作
Line notify 收到
【591新房】 
出錯: Locator.click: Timeout 30000ms exceeded.
Call log:
waiting for get_by_text("All Rights reserved.")
  -   locator resolved to <small>Copyright © 2007-2024 by Addcn Technology Co., Lt…</small>
  - attempting click action
  -   waiting for element to be visible, enabled and stable
  -   element is visible, enabled and stable
  -   scrolling into view if needed
  -   done scrolling
  -   <div class="for-love">…</div> intercepts pointer events
  - retrying click action, attempt #1
  -   waiting for element to be visible, enabled and stable
  -   element is visible, enabled and stable
  -   scrolling into view if needed
  -   done scrolling
  -   <div class="for-love">…</div> intercepts pointer events
  - retrying click action, attempt #2
  -   waiting 20ms
  -   waiting for element to be visible, enabled and stable
  -   element is visible, enabled and stable
  -   scrolling into view if needed
  -   done scrolling
  -   <div class="for-love">…</div> intercepts pointer events
  - retr…

**Comment by seriaati** [comment]
因為我最近爬太頻繁的關係導致被 591 他們注意到了，目前狀況是使用 playwright 一律被檔，不知道他們之後會不會解開。

**Comment by arguskao** [comment]
那您之後會改用其他的方式嗎？例如requests或者selium之類的？

**Comment by seriaati** [comment]
@arguskao 
用requests 沒有辦法，網站內容是用 js 動態生成的
selenium 可以試試

**Comment by arguskao** [comment]
那我期待您的大作囉

**Comment by seriaati** [comment]
由於我自己沒有爬 591 的需求了，加上我覺得用 Selenium 應該也不會有差別，所以先關這個 issue了。
